#!/bin/bash
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ejansen@nvidia.com
#SBATCH --output=outfile-%J
#SBATCH --partition=3080
#SBATCH --time=04:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH packjob
#SBATCH --partition=dgx1
#SBATCH --time=04:00:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1

srun --pack-group=1 env | grep SLURM
srun --pack-group=1 env | grep GPU
echo checkline start
##srun --pack-group=1 nvidia-smi
##srun --pack-group=1 env | grep SLURM
##srun -p 3090 --pty /bin/bash
##srun --pack-group=1 -n 1 -N 1 nvidia-smi -L |grep -c GPU

## Get number of GPU's per node
SLURM_GPUS_PER_NODE_PACK_GROUP_1=$(srun --pack-group=1 -n 1 -N 1 nvidia-smi -L |grep -c GPU)
echo SLURM_GPUS_PER_NODE_PACK_GROUP_1=${SLURM_GPUS_PER_NODE_PACK_GROUP_1}
SLURM_CPUS_ON_NODE_PACK_GROUP_1=$(srun --pack-group=1 -n 1 -N 1 nproc)
echo SLURM_CPUS_ON_NODE_PACK_GROUP_1=${SLURM_CPUS_ON_NODE_PACK_GROUP_1}
SLURM_MEM_PER_NODE_PACK_GROUP_1=$(srun --pack-group=1 -n 1 -N 1 free --mega |grep Mem |awk '{print $2}')
echo SLURM_MEM_PER_NODE_PACK_GROUP_1=${SLURM_MEM_PER_NODE_PACK_GROUP_1}
